### ISSUE TITLE
Unable to Connect to WebSocket Server from Mobile Application (Using Flutter)

### ISSUE THREAD

**Issue by hasancaktar** [zhuovi/XiaoFeng#13]
Hello @zhuovi,

I hope this message finds you well. I have encountered an issue while trying to connect the WebSocket server I created to my mobile application, which is developed using Flutter. Despite multiple attempts, I have been unsuccessful in establishing a connection between the Flutter packages and the server I implemented. I kindly request your assistance in resolving this matter. I am eager for your guidance.

The Flutter packages I am currently using as clients in my application are as follows:

[web_socket_channel](https://pub.dev/packages/web_socket_channel) (the most popular one)
[web_socket_client](https://pub.dev/packages/web_socket_client)
[obs_websocket](https://pub.dev/packages/obs_websocket)

I appreciate any help you can provide in understanding why the mobile application fails to connect to the server. Thank you very much in advance for your support.

Best regards,

**Comment by hasancaktar** [comment]
If you want, I can make a simple application in flutter and post the code.

**Comment by zhuovi** [comment]
Are you using XiaoFeng Socket to implement the webcookie server?
XiaoFeng Socket supports both websocket and socket connections

**Comment by hasancaktar** [comment]
I created normal a websocket server with xiaofeng package. Postman or other clients are connecting. However, as I mentioned earlier, I cannot connect to the server I created with the Xiaofeng library using Flutter. I have tried a lot, but I couldn't establish a connection.



```
using XiaoFeng.Net;

namespace AppserverTest
{
internal class Program
{
static NetServer<ServerSession> server8080 = new NetServer<ServerSession>(8080);


static void Main(string[] args)
{
server8080.OnStart += Server8080_OnStart;
server8080.OnStop += Server8080_OnStop;
server8080.OnDisconnected += Server8080_OnDisconnected;
server8080.OnNewConnection += Server8080_OnNewConnection;
server8080.OnMessage += Server8080_OnMessage;

server8080.Start();
Console.ReadLine();

}

private static void Server8080_OnStop(ISocket socket, EventArgs e)
{
Console.WriteLine("8080 stopped");
}

private static void Server8080_OnStart(ISocket socket, EventArgs e)
{
Console.WriteLine("8080 started");
}


private static void Server8080_OnMessage(INetSession session, string message, EventArgs e)
{
Console.WriteLine("8080 received " + message);
}

private static void Server8080_OnNewConnection(INetSession session, EventArgs e)
{
Console.WriteLine("8080 connected");

session.Send("Merhaba");
}

private static void Server8080_OnDisconnected(INetSession session, EventArgs e)
{
Console.WriteLine("8080 disconnected");
}
}
}
```

**Comment by zhuovi** [comment]
https://sunlogin.oray.com/ You can create a software like this and send me your ID. I can remotely check on your computer to see what the reason is

**Comment by hasancaktar** [comment]
> https://sunlogin.oray.com/ You can create a software like this and send me your ID. I can remotely check on your computer to see what the reason is

Can we use Anydesk 
Anydesk ID: 110195637

I waiting you

**Comment by hasancaktar** [comment]
Hi.

Does Xiaofeng package accept connections with SSL (wss)? In other words, does it support SSL? Are there any additional settings that need to be configured?

**Comment by zhuovi** [comment]
The specific implementation can be found in the XiaoFeng. Redis connection file, which is XiaoFeng/Redis/IO/RedisSocker. cs. This is the client SSL connection, and the server connection requires setting the certificate

**Comment by hasancaktar** [comment]
I need SSL support for the server I'm working on. Currently, I'm using XiaoFeng version 3.3.2 because in later versions, the server stops working after a while. Version 3.3.2 has been running for approximately a month without any issues, so I haven't updated it. Could you please add SSL support to version 3.3.2? I apologize if I'm causing you any inconvenience, and I hope you're not upset with me. Versions above 3.3.2 encounter the error shown in the image, causing the server to stop. However, this issue doesn't exist in version 3.3.2; it is quite stable. My only request is to have SSL support. I really appreciate your assistance, my friend. I love the package you have developed.

![Adsız](https://github.com/zhuovi/XiaoFeng/assets/53625738/57df9730-04df-4a6f-a1d2-3375299624bf)

**Comment by zhuovi** [comment]
Okay, thank you for your support. I will strive to add this SSL feature within this week.

**Comment by hasancaktar** [comment]
> Okay, thank you for your support. I will strive to add this SSL feature within this week.

Hello my friend. When will you release the new update? I'm eager to test it.

**Comment by zhuovi** [comment]
> Hello my friend. When will you release the new update? I'm eager to test it.

We are currently working on SSL communication and it will be ready soon

**Comment by hasancaktar** [comment]
> > Hello my friend. When will you release the new update? I'm eager to test it.
> 
> We are currently working on SSL communication and it will be ready soon

Hello, my friend. I apologize for bothering you. What is the current status of SSL (wss) certificate development? When do you plan to release the new update?

**Comment by zhuovi** [comment]
There have been many updates, and I need to test them carefully. It is expected to be updated by the end of this week

**Comment by hasancaktar** [comment]
> There have been many updates, and I need to test them carefully. It is expected to be updated by the end of this week

Hello @zhuovi,
I hope you are doing well. I just wanted to inquire about the current status of SSL support in your WebSocket package. I understand that everyone can have busy periods and priorities may change.

I am eagerly looking forward to using it as it is crucial for my project. I apologize if my continuous inquiries have been bothersome. 

By the way, I have started using the redis and other features in the package, and you have truly done an excellent job with them.
Best regards,

**Comment by hasancaktar** [comment]
When is the estimated release date for the new update?

**Comment by zhuovi** [comment]
Sorry, we have been working on a project recently and this SSL feature has been delayed repeatedly. We will definitely release a new version in early August. We apologize again.

**Comment by hasancaktar** [comment]
Ok. i'm looking forward to it. Thank you

**Comment by hasancaktar** [comment]
> Sorry, we have been working on a project recently and this SSL feature has been delayed repeatedly. We will definitely release a new version in early August. We apologize again.

Maybe base64 support is also required?

**Comment by zhuovi** [comment]
Base64 byte [] is supported by default. Could you please send me your certificate so that I can test it.

**Comment by hasancaktar** [comment]
The example is provided below. The data that is attempted to be sent as Base64 is not reaching the client, and the server cannot receive the data from the client.




`using System;
using System.Net;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using XiaoFeng.Net;

namespace AppserverTest
{
    internal class Program
    {
        static NetServer<ServerSession> server8080 = new NetServer<ServerSession>(8080);

        static void Main(string[] args)
        {
            server8080.OnStart += Server8080_OnStart;
            server8080.OnStop += Server8080_OnStop;
            server8080.OnDisconnected += Server8080_OnDisconnected;
            server8080.OnNewConnection += Server8080_OnNewConnection;
            server8080.OnMessage += Server8080_OnMessage;

            server8080.Start();
            Console.ReadLine();
        }

        private static void Server8080_OnStart(ISocket socket, EventArgs e)
        {
            Console.WriteLine("8080 started");
        }

        private static void Server8080_OnStop(ISocket socket, EventArgs e)
        {
            Console.WriteLine("8080 stopped");
        }

        private static void Server8080_OnNewConnection(INetSession session, EventArgs e)
        {
            Console.WriteLine("8080 connected");

            // Encrypt and send data
            string message = "Hello";
            string encryptedMessage = EncryptMessage(message);
            session.Send(encryptedMessage);
        }

        private static void Server8080_OnMessage(INetSession session, string message, EventArgs e)
        {
            Console.WriteLine("8080 received " + message);

            // Decrypt and process encrypted data
            string decryptedMessage = DecryptMessage(message);
            Console.WriteLine("Decrypted Message: " + decryptedMessage);
        }

        private static void Server8080_OnDisconnected(INetSession session, EventArgs e)
        {
            Console.WriteLine("8080 disconnected");
        }

        private static string EncryptMessage(string message)
        {
            byte[] key = Encoding.UTF8.GetBytes("YourEncryptionKey123");
            byte[] iv = Encoding.UTF8.GetBytes("YourEncryptionIV456");
            byte[] encryptedBytes;

            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = key;
                aesAlg.IV = iv;

                ICryptoTransform encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);

                using (var msEncrypt = new System.IO.MemoryStream())
                {
                    using (var csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                    {
                        using (var swEncrypt = new System.IO.StreamWriter(csEncrypt))
                        {
                            swEncrypt.Write(message);
                        }

                        encryptedBytes = msEncrypt.ToArray();
                    }
                }
            }

            return Convert.ToBase64String(encryptedBytes);
        }

        private static string DecryptMessage(string encryptedMessage)
        {
            byte[] key = Encoding.UTF8.GetBytes("YourEncryptionKey123");
            byte[] iv = Encoding.UTF8.GetBytes("YourEncryptionIV456");
            byte[] encryptedBytes = Convert.FromBase64String(encryptedMessage);
            string decryptedMessage;

            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = key;
                aesAlg.IV = iv;

                ICryptoTransform decryptor = aesAlg.CreateDecryptor(aesAlg.Key, aesAlg.IV);

                using (var msDecrypt = new System.IO.MemoryStream(encryptedBytes))
                {
                    using (var csDecrypt = new CryptoStream(msDecrypt, decryptor, CryptoStreamMode.Read))
                    {
                        using (var srDecrypt = new System.IO.StreamReader(csDecrypt))
                        {
                            decryptedMessage = srDecrypt.ReadToEnd();
                        }
                    }
                }
            }

            return decryptedMessage;
        }
    }
}
`

**Comment by hasancaktar** [comment]
When I use the encryption structure of this library below, it also gives an error (The input data is not a complete block.).

`
using System;
using System.Net;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using XiaoFeng.Cryptography;
using XiaoFeng.Net;

namespace AppserverTest
{
    internal class Program
    {
        static ICryptography aCryptography = new AESEncryption();
        static NetServer<ServerSession> server8080 = new NetServer<ServerSession>(8080);

        static void Main(string[] args)
        {
            server8080.OnStart += Server8080_OnStart;
            server8080.OnStop += Server8080_OnStop;
            server8080.OnDisconnected += Server8080_OnDisconnected; ;
            server8080.OnNewConnection += Server8080_OnNewConnection;
            server8080.OnMessage += Server8080_OnMessage;
            server8080.OnMessageByte += Server8080_OnMessageByte;

            server8080.Start();
            Console.ReadLine();
        }

        private static void Server8080_OnMessageByte(INetSession session, byte[] message, EventArgs e)
        {

          
          //  string result = message;
        var a =    aCryptography.Decrypt(message, "abc", "123");


        Console.WriteLine(Encoding.ASCII.GetString(a));

           
        }

        private static void Server8080_OnDisconnected(INetSession session, EventArgs e)
        {
            Console.WriteLine("Disconnected");
        }

        private static void Server8080_OnStart(ISocket socket, EventArgs e)
        {
            Console.WriteLine("8080 started");
        }

        private static void Server8080_OnStop(ISocket socket, EventArgs e)
        {
            Console.WriteLine("8080 stopped");
        }

        private static void Server8080_OnNewConnection(INetSession session, EventArgs e)
        {
           
            var a = aCryptography.Encrypt("hello", "abc", "123");
            session.Send(a);
            Console.WriteLine(a);

        }

        private static void Server8080_OnMessage(INetSession session, string message, EventArgs e)
        {
            Console.WriteLine(message);
        }

      
    }
}

`

**Comment by zhuovi** [comment]
var a =    aCryptography.Decrypt(message, "abc", "123");
change into
var bbb = aes.Decrypt(aaa, "abc", "123",OutputMode.Base64);

**Comment by zhuovi** [comment]
I have already restructured the network library, and the certificate I generated myself has been showing issues. I hope you can send me your certificate for testing. Thank you

**Comment by zhuovi** [comment]
@hasancaktar I have already restructured the network library, and the certificate I generated myself has been showing issues. I hope you can send me your certificate for testing. Thank you

**Comment by hasancaktar** [comment]
@zhuovi I have an SSL certificate on the server, and I'm trying to establish a connection from outside using WSS (WebSocket Secure), but it's not working. Normally, when I tried other WebSocket packages, I could connect using both WS and WSS. Do we necessarily need to know about the SSL certificate? Can't we add general SSL support to the package and then connect to a server that has SSL enabled?

**Comment by zhuovi** [comment]
@hasancaktar The socket server needs to configure certificates in PFX format. If you have one, please send it to me.

**Comment by hasancaktar** [comment]
@zhuovi  Unfortunately, I don't have it. SSL is present on the server, and I'm going to connect to this server. The SSL on the server is provided by the side I am on.

**Comment by hasancaktar** [comment]
There are services that provide free SSL certificates. I wonder if we can obtain a result by testing with these certificates?

**Comment by zhuovi** [comment]
I will try to find the free certificate again

**Comment by hasancaktar** [comment]
@zhuovi  I was able to find these: https://letsencrypt.org/ https://zerossl.com/ https://www.openssl.org/

**Comment by hasancaktar** [comment]
@zhuovi Is there anything I can do? If there's any situation where I can help, I'd be glad to assist in any matter.

**Comment by hasancaktar** [comment]
@zhuovi      Hello my friend. I apologize for bothering you. I was wondering about the current status of SSL support.

**Comment by zhuovi** [comment]
@hasancaktar The XiaoFeng class library has released v4.0.0, which supports SSL. The following are examples
Added class libraries SocketServer, SocketClient, WebSocketServer, WebSocketClient;
To prevent bugs in the current class library, it was not upgraded from the original NetServer.

//Only WebSocket connections are supported
var c = new WebSocketServer(8010);
//Supports both Socket and WebSocket connections
//var c = new SocketServer(8010);
c.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
c.Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate(@"E:\\a.eelf.cn.pfx", "7092734");
c.OnStart += (o, e) =>
{
    w("Server Start.");
};
c.OnAuthentication += (c, m, e) =>
{
    //Auth callback
};
c.Authentication = c =>
{
    //auth function
    return true;
};
c.OnStop += (c, e) =>
{
    w("server stop.");
};
c.OnMessage += (c, m, e) =>
{
    w($"recevice message[{c.EndPoint}](text):{m}");
    c.Send(m);
};
c.OnMessageByte += (c, m, e) =>
{
    w($"recevice message[{c.EndPoint}](bytes):{m.GetString()}");
    c.Send(m);
};
c.OnError += (c, e) =>
{
    w("error:" + e.Message);
};
c.OnNewConnection += (c, e) =>
{
    w($"new connection[{c.EndPoint}]");
};
c.OnDisconnected += (c, e) =>
{
    w($"disconnected[{c.EndPoint}]");
};
c.OnClientError += (c, e) =>
{
    w($"client error[{c.EndPoint}]:{e.Message}");
};
c.Start();

**Comment by Hasan188** [comment]
> @hasancaktar The XiaoFeng class library has released v4.0.0, which supports SSL. The following are examples Added class libraries SocketServer, SocketClient, WebSocketServer, WebSocketClient; To prevent bugs in the current class library, it was not upgraded from the original NetServer.
> 
> //Only WebSocket connections are supported var c = new WebSocketServer(8010); //Supports both Socket and WebSocket connections //var c = new SocketServer(8010); c.SslProtocols = System.Security.Authentication.SslProtocols.Tls12; c.Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate(@"E:\a.eelf.cn.pfx", "7092734"); c.OnStart += (o, e) => { w("Server Start."); }; c.OnAuthentication += (c, m, e) => { //Auth callback }; c.Authentication = c => { //auth function return true; }; c.OnStop += (c, e) => { w("server stop."); }; c.OnMessage += (c, m, e) => { w($"recevice message[{c.EndPoint}](text):{m}"); c.Send(m); }; c.OnMessageByte += (c, m, e) => { w($"recevice message[{c.EndPoint}](bytes):{m.GetString()}"); c.Send(m); }; c.OnError += (c, e) => { w("error:" + e.Message); }; c.OnNewConnection += (c, e) => { w($"new connection[{c.EndPoint}]"); }; c.OnDisconnected += (c, e) => { w($"disconnected[{c.EndPoint}]"); }; c.OnClientError += (c, e) => { w($"client error[{c.EndPoint}]:{e.Message}"); }; c.Start();

Thank you very much, my friend. I will try it as soon as I have some free time in the evening. I'm looking forward to it :) Thanks again.

**Comment by hasancaktar** [comment]
> @hasancaktar The XiaoFeng class library has released v4.0.0, which supports SSL. The following are examples Added class libraries SocketServer, SocketClient, WebSocketServer, WebSocketClient; To prevent bugs in the current class library, it was not upgraded from the original NetServer.
> 
> //Only WebSocket connections are supported var c = new WebSocketServer(8010); //Supports both Socket and WebSocket connections //var c = new SocketServer(8010); c.SslProtocols = System.Security.Authentication.SslProtocols.Tls12; c.Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate(@"E:\a.eelf.cn.pfx", "7092734"); c.OnStart += (o, e) => { w("Server Start."); }; c.OnAuthentication += (c, m, e) => { //Auth callback }; c.Authentication = c => { //auth function return true; }; c.OnStop += (c, e) => { w("server stop."); }; c.OnMessage += (c, m, e) => { w($"recevice message[{c.EndPoint}](text):{m}"); c.Send(m); }; c.OnMessageByte += (c, m, e) => { w($"recevice message[{c.EndPoint}](bytes):{m.GetString()}"); c.Send(m); }; c.OnError += (c, e) => { w("error:" + e.Message); }; c.OnNewConnection += (c, e) => { w($"new connection[{c.EndPoint}]"); }; c.OnDisconnected += (c, e) => { w($"disconnected[{c.EndPoint}]"); }; c.OnClientError += (c, e) => { w($"client error[{c.EndPoint}]:{e.Message}"); }; c.Start();

Thank you very much, my friend. I will try it as soon as I have some free time in the evening. I'm looking forward to it :) Thanks again.

**Comment by hasancaktar** [comment]
> 

@zhuovi I've tested it as a regular server. When I connect using Postman, it gives the following error. There are no issues during the initial connection, but when I rapidly establish and terminate the connection a few times, it produces the error shown in the image.

It seems that there is no ping-pong mechanism in the SocketServer. The ping mechanism in NetServer works quite well. We can determine both the ping interval and the number of ping messages before closing the client session. I wonder if we can also add a ping-pong mechanism to the SocketServer.

[Error]
![resim](https://github.com/zhuovi/XiaoFeng/assets/53625738/cae8fc27-b88a-4cd2-86f7-e714f1b1eec8)

![resim](https://github.com/zhuovi/XiaoFeng/assets/53625738/fd4e149c-370f-4db3-8184-be35e6f3a13b)

**Comment by zhuovi** [comment]
There is an IsPong=true and PongTime=120 attribute in this. Previously, ping pong used to send messages to determine the impact on the business, but now it uses protocol ping pong, which does not affect the business. Of course, data can also be brought into the pong. If you really want to increase the original effect, you can do this: 
`new Job(). Interval (120 * 1000). SetCompleteCallBack (job=>
{
Ws. SendAsync ("{type:'pong '}");
}. Start();`

**Comment by zhuovi** [comment]
@hasancaktar If you have any problems using it, I can help you debug it remotely. The current refactoring approach is much better than before

**Comment by hasancaktar** [comment]
@zhuovi There is no ping feature in SocketServer. It exists in WebSocketServer, but when I set IsPong to true, clients that don't receive the pong message are still remaining connected. In fact, I would like to connect remotely and demonstrate. It can remain open and accessible. Anydesk: 110 195 637

**Comment by hasancaktar** [comment]
Hi @zhuovi . When will you release the new update on NuGet? When I quickly open and close connections in the server I created with SocketServer, just like in the old error, it gives the error shown in the image (in Postman). I couldn't achieve the ping pong mechanism as I did in NetServer. In other words, even if I don't send a pong message to the server when the client is connected, the session doesn't close, and it still writes logs to the console. The Headers property that exists in NetServer is not present in SocketServer. Could you add that too? Because when the client connects as "ws://0.0.0.0:8000/test", I was able to read the "test" value from the header. Actually, NetServer is working quite stably for me. I would be very happy if we could add SSL support to this class. Of course, if SocketServer would be better, you know best.

![WhatsApp Image 2023-08-09 at 21 40 58](https://github.com/zhuovi/XiaoFeng/assets/53625738/8cde81e6-071b-4d82-b3dc-1457c165ec71)

**Comment by hasancaktar** [comment]
@zhuovi Hi. If I'm bothering you, I apologize. If you're available this week, could we establish a connection via AnyDesk?

**Comment by hasancaktar** [comment]
> //var c = new SocketServer(8010);
> c.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
> c.Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate(@"E:\a.eelf.cn.pfx", "7092734");
> c.OnStart += (o, e) =>
> {
> w("Server Start.");
> };
> c.OnAuthentication += (c, m, e) =>
> {
> //Auth callback
> };
> c.Authentication = c =>
> {
> //auth function
> return true;
> };
> c.OnStop += (c, e) =>
> {
> w("server stop.");
> };
> c.OnMessage += (c, m, e) =>
> {
> w($"recevice message[{c.EndPoint}](text):{m}");
> c.Send(m);
> };
> c.OnMessageByte += (c, m, e) =>
> {
> w($"recevice message[{c.EndPoint}](bytes):{m.GetString()}");
> c.Send(m);
> };
> c.OnError += (c, e) =>
> {
> w("error:" + e.Message);
> };
> c.OnNewConnection += (c, e) =>
> {
> w($"new connection[{c.EndPoint}]");
> };
> c.OnDisconnected += (c, e) =>
> {
> w($"disconnected[{c.EndPoint}]");
> };
> c.OnClientError += (c, e) =>
> {
> w($"client error[{c.EndPoint}]:{e.Message}");
> };
> c.Start();


Hello my friend. I apologize for bothering you. The onDisconnected event is not being triggered in the code. I'm still encountering the error I mentioned above. I believe the issue might be due to receiving a null value during the handshake process.

[test]
`static void Main(string[] args)
        {
            var c = new SocketServer(8010);
            //c.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
            //c.Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate(@"E:\a.eelf.cn.pfx", "7092734");
            c.OnStart += (o, e) =>
            {
                Console.WriteLine("Server Start.");
            };
            c.OnAuthentication += (c, m, e) =>
            {
                //Auth callback
            };
            c.Authentication = c =>
            {
                //auth function
                return true;
            };
            c.OnStop += (c, e) =>
            {
                Console.WriteLine("server stop.");
            };
            c.OnMessage += (c, m, e) =>
            {
                Console.WriteLine($"recevice message{c.EndPoint}:{m}");
                c.Send(m);
            };
            c.OnMessageByte += (c, m, e) =>
            {
                Console.WriteLine($"recevice message{c.EndPoint}:{m.GetString()}");
                c.Send(m);
            };
            c.OnError += (c, e) =>
            {
                Console.WriteLine("error:" + e.Message);
            };
            c.OnNewConnection += (c, e) =>
            {
                Console.WriteLine($"new connection[{c.EndPoint}]");
            };
            c.OnDisconnected += (c, e) =>
            {
                Console.WriteLine($"disconnected[{c.EndPoint}]");
            };
            c.OnClientError += (c, e,m) =>
            {
                Console.WriteLine("client error");
            };
            c.Start();
            Console.ReadLine();
        }`

**Comment by zhuovi** [comment]
Can you test it more? I will also test it on my end. Last week, I went out of town and didn't update. I will fix what you mentioned in the next few days before releasing it

**Comment by hasancaktar** [comment]
> Can you test it more? I will also test it on my end. Last week, I went out of town and didn't update. I will fix what you mentioned in the next few days before releasing it

Could you provide me with an example .pfx file? I'll be testing it with the Netserver object, as the NetServer object is more stable in my experience.

**Comment by zhuovi** [comment]
@hasancaktar windows 证书管理->个人->证书 localhost这个证书就可以用

**Comment by hasancaktar** [comment]
@zhuovi  Hi . I have created and attached the file, but I am unable to establish a connection. There is no error indicated either. If you're available, do you have a chance to connect to my remote computer? Anydesk 328 075 286

**Comment by zhuovi** [comment]
@hasancaktar The latest version 4.0.1 has been released. You can contact me around 17:30 Beijing time to help you remotely

**Comment by hasancaktar** [comment]
> 

can you connect anydesk 110 195 637

**Comment by hasancaktar** [comment]
@zhuovi When I test it now, if I quickly close and reopen the connection, it fails with an error. The most likely reason for the error is that the handshake is coming as null, and the connection cannot be established. Could you please look into this issue?
![resim](https://github.com/zhuovi/XiaoFeng/assets/53625738/de644519-93c7-4c58-9337-cc1f5899e513)

**Comment by zhuovi** [comment]
@hasancaktar i test tomorrow

**Comment by hasancaktar** [comment]
> @hasancaktar i test tomorrow

You can test it using either the WebSocketKing.com website or Postman through the console application.

**Comment by zhuovi** [comment]
@hasancaktar  
I tested as follows
![image](https://github.com/zhuovi/XiaoFeng/assets/16105174/bc15dfed-0705-40c5-b7a2-beafe06c953d)

Your problem is mainly that when using sockets in your business, you need to determine whether their status is disconnected or empty, such as (client!=null&&&client. Connected). In this case, you can proceed with socket processing, and you also need to add try {} catch (Excetpion ex) {} when processing because it may be disconnected by the client at any time.

**Comment by hasancaktar** [comment]
Most of the time, it doesn't establish a connection when I first start the server. In other words, without checking whether the client's connection is severed or not. When I debug the program, it seems like it can't perform the handshake because the sec key is coming as null. I tried to demonstrate it in the images, but you would understand much better. I also included the sample code I wrote myself.

[code]
 internal class Program
    {
        public static SocketServer server = new SocketServer(8011);
        static void Main(string[] args)
        {
            try
            {

                server.Certificate = new X509Certificate2(@"C:\Users\iar545\Desktop\pfx\f.pfx", "7092734", X509KeyStorageFlags.MachineKeySet);
                server.SslProtocols = SslProtocols.None;
               
                server.OnStart += Server_OnStart;
                server.OnAuthentication += Server_OnAuthentication;
                server.OnStop += Server_OnStop;
                server.OnMessage += Server_OnMessage;
                server.OnError += Server_OnError;
                server.OnNewConnection += Server_OnNewConnection;
                server.OnDisconnected += Server_OnDisconnected;
                server.OnClientError += Server_OnClientError;

                server.IsPong = true;
                server.PongTime = 30;

                server.Start();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            Console.ReadLine();
        }

        private static void Server_OnError(INetSocket socket, Exception e)
        {
            Console.WriteLine($"Server error: {socket.EndPoint}");
        }

        private static void Server_OnClientError(ISocketClient client, System.Net.IPEndPoint endPoint, Exception e)
        {
            Console.WriteLine($"Client error: {client.EndPoint}");
        }

        private static void Server_OnDisconnected(ISocketClient client, EventArgs e)
        {
            Console.WriteLine($"Client disconnected: {client.EndPoint}");
        }

        private static void Server_OnNewConnection(ISocketClient client, EventArgs e)
        {
            Console.WriteLine($"Client connected: {client.EndPoint}");
        }

        private static void Server_OnMessage(ISocketClient client, string message, EventArgs e)
        {
            Console.WriteLine($"Receive message: {client.EndPoint}");
        }

        private static void Server_OnStop(INetSocket socket, EventArgs e)
        {
            Console.WriteLine($"Server stop");
        }

        private static void Server_OnAuthentication(ISocketClient client, string message, EventArgs e)
        {
            Console.WriteLine($"Auth: {message}");
        }

        private static void Server_OnStart(INetSocket socket, EventArgs e)
        {
            Console.WriteLine($"server start");
        }
    }


![null](https://github.com/zhuovi/XiaoFeng/assets/53625738/385f7632-c187-42f4-b7ee-f5118a11386d)
![success](https://github.com/zhuovi/XiaoFeng/assets/53625738/fd6f2723-30cc-4875-bd47-72c4aee9fbec)
![connected](https://github.com/zhuovi/XiaoFeng/assets/53625738/4b91d2ab-816c-4694-856a-77b9a78e543d)
![notcon](https://github.com/zhuovi/XiaoFeng/assets/53625738/c3f32f1c-f3f1-42a3-abf3-1e0f6d02544e)

**Comment by zhuovi** [comment]
@hasancaktar server.SslProtocols 用1.2试一下

**Comment by hasancaktar** [comment]
> @hasancaktar server.SslProtocols 用1.2试一下

yes i use it that way.

  server.Certificate = new X509Certificate2(@"C:\Users\iar545\Desktop\pfx\f.pfx", "7092734", X509KeyStorageFlags.MachineKeySet);

server.SslProtocols = SslProtocols.Tls12;

**Comment by zhuovi** [comment]
@hasancaktar AnyDesk sent to me

**Comment by hasancaktar** [comment]
> @hasancaktar AnyDesk sent to me

can you connect me?

**Comment by hasancaktar** [comment]
> @hasancaktar AnyDesk sent to me

I believe I'm not able to receive the message from the client quickly. If you're available, could you take a look?

**Comment by hasancaktar** [comment]
@zhuovi The messages coming from Postman are arriving slowly. There's no issue with the ones coming from the web.

**Comment by zhuovi** [comment]
@hasancaktar I didn't understand what you said

**Comment by hasancaktar** [comment]
> dn't understand what you said

can you connect anydesk. if you avaible

**Comment by hasancaktar** [comment]
When I connect to the server and send a message using Postman, the server takes a long time to receive the message. However, if the server sends a message to the client immediately after receiving a message, there's no issue. I think when the client sends a message, the server needs to send a message as well.

**Comment by zhuovi** [comment]
@hasancaktar You accept your anydesk

**Comment by hasancaktar** [comment]
> @hasancaktar You accept your anydesk

I apologize, but I wasn't near the computer. I'm available now, so you can connect.

**Comment by hasancaktar** [comment]
My internet closed. Wait a Few minutes please

**Comment by hasancaktar** [comment]
You can connect
