### ISSUE TITLE
 OnNewConnection event not triggered for socket-type client connections

### ISSUE THREAD

**Issue by hasancaktar** [zhuovi/XiaoFeng#14]
I apologize for any inconvenience caused, my friend. The OnNewConnection event doesn't seem to be triggered when a client with a socket connection type is connected to the server. The event only appears to trigger when the client sends a message. To investigate this matter, I tested it on the SocketServer class, as it supports socket connections.

Would it be possible for you to examine this bug? This holds significance for me, given that the type of connection our client employs is a socket. I rely on adding the connected client to a list based on its status, but currently, I'm unable to do so without the client sending a message.

A client tool with socket connection capabilities: [Hercules Setup Utility](https://www.hw-group.com/software/hercules-setup-utility)

**Comment by zhuovi** [comment]
@hasancaktar I thought about this issue last night and was thinking about how to handle the current bug. The current idea is to add an OnHandshakeCompleted event. The current event is for the event triggered after the web handshake is completed, and OnNewConnection is to trigger the current event as soon as the connection is connected. If it is a socket socket connection, only OnNewConnection will be triggered. If it is a WebSocket connection, the OnNewConnection event will be triggered first, After the handshake is completed, communication can begin and the OnHandshakeCompleted event is triggered. This is a temporary plan that I came up with last night

**Comment by hasancaktar** [comment]
In the server (netserver class) I used before, there was no issue like this. Both socket and WebSocket connections reliably triggered the OnNewConnection event. We can make a similar adjustment to the structure there. 

If you're available, you can connect to me.
Anydesk 110 195 637

**Comment by zhuovi** [comment]
In NetServer, OnNewConnection was triggered on the first connection and the first message received was verified to be websocket. Then, the current object connection type was set to websocket. To put it bluntly, no event was triggered after the handshake was successful, but the current client object was set to websocket. What I am thinking of now is that you need to send a message to the client in OnNewConnection, But at this point, if it is a socket, your message can be successfully sent. If it is a websocket, the server will disconnect the current connection because it is a websocket,

**Comment by hasancaktar** [comment]
@zhuovi In the case where the connection is of socket type, OnNewConnection isn't triggered initially, which prevents the ability to send a message during the first connection, until the client sends a message. It gets triggered when a message is received from the client. This situation could potentially pose a problem. If thousands of sockets connect to the server without sending any messages, the server won't be able to identify the connected clients. This could lead to occupied ports, filled buffers, and potentially other errors. Of course, you're more experienced in this matter and have a better understanding.

**Comment by zhuovi** [comment]
@hasancaktar The new version has resolved the OnNewConnection issue in Socket and WebSocket connections, with version: v 4.1.0

**Comment by hasancaktar** [comment]
> The new version has resolved the OnNewConnection issue in Socket and WebSocket connections, with version: v 4.1.0

Thank you so much. I will test now

**Comment by hasancaktar** [comment]
> @hasancaktar The new version has resolved the OnNewConnection issue in Socket and WebSocket connections, with version: v 4.1.0

When will you publish it to NuGet?

**Comment by hasancaktar** [comment]
> @hasancaktar The new version has resolved the OnNewConnection issue in Socket and WebSocket connections, with version: v 4.1.0
When I send a message to the server over the socket, the connection is getting lost, and it's giving the error shown in the image.
In WebSocket, the representation of messages received in OnMessage and OnMessageByte functions differs. If you'd like, you can show me how to connect to my computer. I'm available.
![resim](https://github.com/zhuovi/XiaoFeng/assets/53625738/4427d851-c4b1-47b5-8c9f-226bd114a159)

**Comment by zhuovi** [comment]
It is because your SocketClient did not use a certificate to connect to a SocketServer that requires a certificate. Your SocketClient can also use a certificate

**Comment by hasancaktar** [comment]
@zhuovi It seems that the socket cannot send messages to a server with SSL because it lacks SSL support. This conclusion arises from the fact that when SSL is removed, sending messages does not cause any issues.

> It is because your SocketClient did not use a certificate to connect to a SocketServer that requires a certificate. Your SocketClient can also use a certificate

**Comment by hasancaktar** [comment]
> It is because your SocketClient did not use a certificate to connect to a SocketServer that requires a certificate. Your SocketClient can also use a certificate

It seems that the socket cannot send messages to a server with SSL because it lacks SSL support. This conclusion arises from the fact that when SSL is removed, sending messages does not cause any issues.

**Comment by zhuovi** [comment]
> 

YES

**Comment by hasancaktar** [comment]
> > 
> 
> YES

Ok i understand

**Comment by hasancaktar** [comment]
@zhuovi 



![resim](https://github.com/zhuovi/XiaoFeng/assets/53625738/74acc6c0-281b-4786-b5a4-8454042a36cd)
