### ISSUE TITLE
Sending messages between clients connected to the server.

### ISSUE THREAD

**Issue by hasancaktar** [zhuovi/XiaoFeng#5]
I am sending messages to all clients connected to the server that I created using this package, but I cannot send messages specifically between two clients. Can you show a small example please?

my simple code:

`private static void OnMessage(object sender, string message, EventArgs e)
        {
            Console.WriteLine("Received: " + message);
        
            if (sender is SocketConnection)
            {
                foreach (var client in clients)
                {                 
                    server.Send(message,client);
                }
            }
        }`

**Comment by zhuovi** [comment]
private static void OnMessage（object sender， string message， EventArgs e）
{
Console.WriteLine（“Received： ” + message）;
var client = sender as SocketConnection;
//Reply to the current client
client.Send(message);
    }

**Comment by hasancaktar** [comment]
> private static void OnMessage（object sender， string message， EventArgs e） { Console.WriteLine（“Received： ” + message）; var client = sender as SocketConnection; //Reply to the current client client.Send(message); }

This is not exactly what I want to ask. For example, 3 clients are connected to the server. I want to send a message between the first and third client connected, so I want the first client to be able to send a direct message to the third client.

**Comment by zhuovi** [comment]
That can't be sent, because the two clients are not directly connected. You can transfer through the server, which means you send the command with whom, and then send it to the client after the server receives it. Each client adds an identifying name. The other is the communication between two clients.

**Comment by zhuovi** [comment]
For example, client A, client B, server C, A sends messages containing the identity of client B, sends data to server C, and C receives messages that are sent to client B, and forwards them directly to client B. Another way is that client A connects to client B directly, because you don't know the IP of client B, then all clients connect to the server IP, and the port is unified by default. Client A connects to C, B connects to C, A gets the IP of B through C, and A connects to B for communication.

**Comment by hasancaktar** [comment]
I understand the logic. Then, when the customer sends a message, the message should contain the information of the customer to whom he wants to send this message. Did I get right?

**Comment by zhuovi** [comment]
> 

YES

**Comment by hasancaktar** [comment]
I want to examine something more. When I try it in Postman it accepts whatever I type in the web-socket-verison field. How did you do this setting? It only supports version 13 in other packages I tried. Your package is beautiful. It supports all versions.


![123](https://user-images.githubusercontent.com/53625738/216965376-701bbf85-525c-4168-b738-60f0eee44ca0.png)

**Comment by zhuovi** [comment]
> 我想检查更多的东西。当我在Postman中尝试它时，它接受我在web-socket-verison字段中键入的任何内容。您是如何进行此设置的？它只支持我尝试过的其他软件包中的版本 13。你的包裹很漂亮。它支持所有版本。
> 
> ![123](https://user-images.githubusercontent.com/53625738/216965376-701bbf85-525c-4168-b738-60f0eee44ca0.png)

I haven't done anything about this Sec-WebSocket-Version, just ignore it

**Comment by hasancaktar** [comment]
I am sorry for disturbing you. When I want to connect to the server I created, it connects twice. I used the ServerSession class.

![32](https://user-images.githubusercontent.com/53625738/216973643-8c91c311-425d-4e4c-a167-e5a5f58de24e.png)



My Codes: 

`internal class Program
    {

        static XiaoFeng.Net.NetServer<XiaoFeng.Net.ServerSession> socketServer = new XiaoFeng.Net.NetServer<XiaoFeng.Net.ServerSession>("127.0.0.1", 8080);


        static  List<EndPoint> clients =new List<EndPoint>();

        static void Main(string[] args)
        {
           
          

            socketServer.OnDisconnected += OnDisconnected;
            socketServer.OnNewConnection += OnNewConnection;
            socketServer.OnMessage += OnMessage;
            socketServer.OnStart += OnStart;
            socketServer.OnStop += OnStop;
            socketServer.OnClientError += OnClientError;
            socketServer.OnError += OnError;

            socketServer.Start();

         
            
            
           

            //SocketServer.AddIpBlack("124.2.2.2");
            Console.ReadLine();
        }

        private static void OnError(XiaoFeng.Net.ISocket socket, System.Net.Sockets.SocketException e)
        {
            Console.WriteLine("OnError: " + socket.GetValue());
        }

        private static void OnClientError(XiaoFeng.Net.INetSession session, System.Net.Sockets.SocketException e)
        {
            Console.WriteLine("OnClientError: " + e.Message);
        }

        private static void OnStop(XiaoFeng.Net.ISocket socket, EventArgs e)
        {
            Console.WriteLine("OnStop: " + socket.GetValue());
        }

        private static void OnStart(XiaoFeng.Net.ISocket socket, EventArgs e)
        {
            Console.WriteLine("OnStart");
        }

        private static void OnMessage(XiaoFeng.Net.INetSession session, string message, EventArgs e)
        {
            Console.WriteLine("Message: "+message +" | " +session.EndPoint);
        }

        private static void OnNewConnection(XiaoFeng.Net.INetSession session, EventArgs e)
        {

            Console.WriteLine("OnNewConnection: " + session.EndPoint);
            session.Send("client");
        }

        private static void OnDisconnected(XiaoFeng.Net.INetSession session, EventArgs e)
        {
            Console.WriteLine("OnDisconnected: " + session.EndPoint);
        }
    }`

**Comment by zhuovi** [comment]
> 很抱歉打扰你了。当我想连接到我创建的服务器时，它会连接两次。我使用了服务器会话类。
> 
> ![32](https://user-images.githubusercontent.com/53625738/216973643-8c91c311-425d-4e4c-a167-e5a5f58de24e.png)
> 
> 我的代码：
> 
> '内部课程计划 {
> 
> ```
>     static XiaoFeng.Net.NetServer<XiaoFeng.Net.ServerSession> socketServer = new XiaoFeng.Net.NetServer<XiaoFeng.Net.ServerSession>("127.0.0.1", 8080);
> 
> 
>     static  List<EndPoint> clients =new List<EndPoint>();
> 
>     static void Main(string[] args)
>     {
>        
>       
> 
>         socketServer.OnDisconnected += OnDisconnected;
>         socketServer.OnNewConnection += OnNewConnection;
>         socketServer.OnMessage += OnMessage;
>         socketServer.OnStart += OnStart;
>         socketServer.OnStop += OnStop;
>         socketServer.OnClientError += OnClientError;
>         socketServer.OnError += OnError;
> 
>         socketServer.Start();
> 
>      
>         
>         
>        
> 
>         //SocketServer.AddIpBlack("124.2.2.2");
>         Console.ReadLine();
>     }
> 
>     private static void OnError(XiaoFeng.Net.ISocket socket, System.Net.Sockets.SocketException e)
>     {
>         Console.WriteLine("OnError: " + socket.GetValue());
>     }
> 
>     private static void OnClientError(XiaoFeng.Net.INetSession session, System.Net.Sockets.SocketException e)
>     {
>         Console.WriteLine("OnClientError: " + e.Message);
>     }
> 
>     private static void OnStop(XiaoFeng.Net.ISocket socket, EventArgs e)
>     {
>         Console.WriteLine("OnStop: " + socket.GetValue());
>     }
> 
>     private static void OnStart(XiaoFeng.Net.ISocket socket, EventArgs e)
>     {
>         Console.WriteLine("OnStart");
>     }
> 
>     private static void OnMessage(XiaoFeng.Net.INetSession session, string message, EventArgs e)
>     {
>         Console.WriteLine("Message: "+message +" | " +session.EndPoint);
>     }
> 
>     private static void OnNewConnection(XiaoFeng.Net.INetSession session, EventArgs e)
>     {
> 
>         Console.WriteLine("OnNewConnection: " + session.EndPoint);
>         session.Send("client");
>     }
> 
>     private static void OnDisconnected(XiaoFeng.Net.INetSession session, EventArgs e)
>     {
>         Console.WriteLine("OnDisconnected: " + session.EndPoint);
>     }
> }`
> ```

You clicked twice

**Comment by hasancaktar** [comment]
I clicked once. As seen in the picture, the port numbers of the connected clients are the same. You can also test the code.

**Comment by zhuovi** [comment]
> 

Okay, let me test it

**Comment by zhuovi** [comment]
> 我点击了一次。如图所示，连接的客户端的端口号相同。您还可以测试代码。

The bug has been submitted. The OnNewConnection was also called after the websocket handshake was successful. It is in line 556 of the file ServerSession.cs. After the comment, it is OK. Thank you for your information.

**Comment by hasancaktar** [comment]
I am currently developing a project with this package. When will the forecast be fixed?

**Comment by zhuovi** [comment]
> I am currently developing a project with this package. When will the forecast be fixed?

The code has been submitted. It is in the ServerSession.cs file and has been submitted to github. The package has not been released.

**Comment by hasancaktar** [comment]
> > I am currently developing a project with this package. When will the forecast be fixed?
> 
> The code has been submitted. It is in the ServerSession.cs file and has been submitted to github. The package has not been released.

How can I apply this change you made to my project? I tried a little but I couldn't

**Comment by zhuovi** [comment]
> 

You are referring to a project or a package on nuget. If it is a project, you can pull it again. If it is a package, I will pack it tomorrow

**Comment by hasancaktar** [comment]
> > 
> 
> You are referring to a project or a package on nuget. If it is a project, you can pull it again. If it is a package, I will pack it tomorrow

I asked him when he would publish the change in this package, that is, the change on line 556. I think you will tomorrow. thank you

**Comment by zhuovi** [comment]
> > > 
> > 
> > 
> > You are referring to a project or a package on nuget. If it is a project, you can pull it again. If it is a package, I will pack it tomorrow
> 
> I asked him when he would publish the change in this package, that is, the change on line 556. I think you will tomorrow. thank you

XiaoFeng V3.3.2 has been released. Please go to nuget to download it.
