### ISSUE TITLE
It might be better to change the parameter of the OnDisconnected event.

### ISSUE THREAD

**Issue by hasancaktar** [zhuovi/XiaoFeng#6]
`private static void OnDisconnected(EndPoint sender, EventArgs e)`

It would be better if you make the parameter of the OnDisconnected event as SocketConnection sender like the parameters of the OnNewConnection event. Because we can better handle the disconnected client. 

Like this: `private static void OnDisconnected(SocketConnection sender, EventArgs e)`

**Comment by zhuovi** [comment]
Because the SocketConnection object has been released after the connection is disconnected, and it is meaningless to send it back.

**Comment by hasancaktar** [comment]
I add it to the list when the new licent is connected. but when the connection is lost I cannot remove it from the list because the parameter of the ondisconneted event does not match.

![12](https://user-images.githubusercontent.com/53625738/216957273-08f94141-f02d-43dd-bee5-4ce14e5c0a37.png)

**Comment by zhuovi** [comment]
You can use dictionaries, such as Dictionary<Endpoint, SocketConnection>or ConcurrentDictionary<Endpoint, SocketConnection>.
The server has a method like IServerSession [] GetData(), which can get all the current clients.
