### ISSUE TITLE
Error Server Start and Stop

### ISSUE THREAD

**Issue by hasancaktar** [zhuovi/XiaoFeng#9]
Hello. I couldn't get the start and stop functions of the servers to work. I started two servers and tried to start and stop the second server according to the start and stop messages sent from the first server, but when the server is stopped, it doesn't start again. Actually, it starts, but it cannot detect the incoming messages and it cannot be stopped again.

The code is as follows:

`internal class Program
    {
      static NetServer<ServerSession> server9090 = new NetServer<ServerSession>(9090);
      static NetServer<ServerSession> server8080 = new NetServer<ServerSession>(8080);
     
      static List<INetSession> server9090ClientList = new List<INetSession>();
      static List<INetSession> server8080ClientList = new List<INetSession>();

        static void Main(string[] args)
        {
           

        server9090.OnStart += Server9090_OnStart;
            server9090.OnStop += Server9090_OnStop;
            server9090.OnNewConnection += Server9090_OnNewConnection;
            server9090.OnDisconnected += Server9090_OnDisconnected;
            server9090.OnMessage += Server9090_OnMessage;

            server8080.OnStart += Server8080_OnStart;
            server8080.OnStop += Server8080_OnStop;
            server8080.OnNewConnection += Server8080_OnNewConnection;
            server8080.OnDisconnected += Server8080_OnDisconnected;
            server8080.OnMessage += Server8080_OnMessage;

            server9090.Start();
            server8080.Start();

            Console.ReadLine();
        }
        private static void Server9090_OnStart(ISocket socket, EventArgs e)
        {
            Console.WriteLine($"9090 Started");
        }
        private static void Server9090_OnStop(ISocket socket, EventArgs e)
        {
            Console.WriteLine($"9090 Stopped");
        }

        private static void Server9090_OnMessage(INetSession session, string message, EventArgs e)
        {
            Console.WriteLine($"9090 Received: {message}");
        }

        private static void Server9090_OnNewConnection(INetSession session, EventArgs e)
        {

            server9090ClientList.Add(session);
            Console.WriteLine($"9090 Clinet connected: {session.EndPoint}");
            
        }

        private static void Server9090_OnDisconnected(INetSession session, EventArgs e)
        {
            server9090ClientList.Remove(session);
            Console.WriteLine($"9090 Clinet disconnected: {session.EndPoint}");
        }

        //-----------------------------------//

        private static void Server8080_OnStart(ISocket socket, EventArgs e)
        {
            Console.WriteLine($"8080 Started");
        }

        private static void Server8080_OnStop(ISocket socket, EventArgs e)
        {
            Console.WriteLine($"8080 Stopped");
        }
        private static void Server8080_OnNewConnection(INetSession session, EventArgs e)
        {
            server8080ClientList.Add(session);
            Console.WriteLine($"8080 Clinet connected: {session.EndPoint}");
        }
        private static void Server8080_OnDisconnected(INetSession session, EventArgs e)
        {
            server8080ClientList.Remove(session);
            Console.WriteLine($"8080 Clinet disconnected: {session.EndPoint}");
        }

        
        private static void Server8080_OnMessage(INetSession session, string message, EventArgs e)
        {
            Console.WriteLine($"8080 Received: {message}");

            if (message.Contains("start"))
            {
                server9090.Start();
            }

            if (message.Contains("stop"))
            {
                //server9090.Stop();
                server9090.Close();
                //server9090.Dispose();
                //server9090.ClientSocket.Close();
                //server9090.ClientSocket.Shutdown(SocketShutdown.Receive);
            }
        }
    }`

![123a](https://user-images.githubusercontent.com/53625738/224065004-1455e0ba-48d5-4ff8-ab1a-9266fb449969.png)

I also get this error when I try the Shutdown function:
![321](https://user-images.githubusercontent.com/53625738/224072977-fadd4402-45eb-4ef1-935b-2c8321325bb3.png)

**Comment by zhuovi** [comment]
Thank you for your feedback. There are indeed such bugs, which are caused by the failure of initialization and the failure to start the receiving client connection thread after the cancellation instruction is cancelled. nuget xiaofeng.v3.4.1Published

**Comment by hasancaktar** [comment]
I have tested the changes and there is still a small bug. I will give an example based on the following code. When I start the console application, the servers start. When I send a "stop" message to server2020, the functions "server1010.ClientSocket.Close();" and "server1010.ClientSocket.Dispose();" close the server. It does not accept new connection requests but does not close the connections of the clients already connected. The connections of the connected clients also need to be closed.

When the functions "server1010.Stop();" and "server1010.Dispose();" are executed, the server is closed and the connected clients are also closed. When it is started again, the client connection is made, but it is not displayed on the screen and does not show the messages received by the server. So, the old problem continues.

If you want to try, you can use the sample code I have tested:


` internal class Program
    {
        static NetServer<ServerSession> server1010 = new NetServer<ServerSession>(1010);
        static NetServer<ServerSession> server2020 = new NetServer<ServerSession>(2020);

        static void Main(string[] args)
        {
            server1010.OnStart += Server1010_OnStart;
            server1010.OnStop += Server1010_OnStop;
            server1010.OnDisconnected += Server1010_OnDisconnected;
            server1010.OnNewConnection += Server1010_OnNewConnection;
            server1010.OnMessage += Server1010_OnMessage;

            server2020.OnStart += Server2020_OnStart;
            server2020.OnStop += Server2020_OnStop;
            server2020.OnDisconnected += Server2020_OnDisconnected;
            server2020.OnNewConnection += Server2020_OnNewConnection;
            server2020.OnMessage += Server2020_OnMessage;

            server1010.Start();
            server2020.Start();
           
            Console.ReadLine();

        }
        private static void Server2020_OnMessage(INetSession session, string message, EventArgs e)
        {
            Console.WriteLine("2020 received " + message);
            if (message.Contains("start"))
            {
                server1010.Start();

            }

            if (message.Contains("stop"))
            {
                //server1010.Stop();
                //server1010.Dispose();
                server1010.ClientSocket.Close();
                //server1010.ClientSocket.Dispose();
               
            }
        }
        private static void Server2020_OnStop(ISocket socket, EventArgs e)
        {
            Console.WriteLine("2020 stopped");
        }

        private static void Server2020_OnStart(ISocket socket, EventArgs e)
        {
            Console.WriteLine("2020 started");
        }
        private static void Server1010_OnStop(ISocket socket, EventArgs e)
        {
            Console.WriteLine("1010 stopped");
        }

        private static void Server1010_OnStart(ISocket socket, EventArgs e)
        {
            Console.WriteLine("1010 started");
        }
        private static void Server2020_OnNewConnection(INetSession session, EventArgs e)
        {
            Console.WriteLine("2020 connected");
        }

        private static void Server2020_OnDisconnected(INetSession session, EventArgs e)
        {
            Console.WriteLine("2020 disconnected");
        }

        private static void Server1010_OnMessage(INetSession session, string message, EventArgs e)
        {
            Console.WriteLine("1010 received "+message);
        }

        private static void Server1010_OnNewConnection(INetSession session, EventArgs e)
        {
            Console.WriteLine("1010 connected");
        }

        private static void Server1010_OnDisconnected(INetSession session, EventArgs e)
        {
            Console.WriteLine("1010 disconnected");
        }
    }`

**Comment by zhuovi** [comment]
My test client is also disconnected. I use websocket connection. When the server is stopped, all clients in the online list will be disconnected and cleared.

**Comment by zhuovi** [comment]
My test client is also disconnected. I use websocket connection. When the server is stopped, all clients in the online list will be disconnected and cleared.

**Comment by zhuovi** [comment]
You use Server1010. Stop() to stop

**Comment by hasancaktar** [comment]
As you said it disconnects and cleans up client connections, but it does this only once. When I send the "start" message again, server1010 starts, but when I send the "stop" message again, the stop function does not work.

**Comment by zhuovi** [comment]
> As you said it disconnects and cleans up client connections, but it does this only once. When I send the "start" message again, server1010 starts, but when I send the "stop" message again, the stop function does not work.

I'll test it when I get home in the evening

**Comment by zhuovi** [comment]
> As you said it disconnects and cleans up client connections, but it does this only once. When I send the "start" message again, server1010 starts, but when I send the "stop" message again, the stop function does not work.

Bugs have been fixed, github has been submitted, nuget has been released, and the version is 3.4.2

**Comment by hasancaktar** [comment]
I tested it and it works. Thank you very much

**Comment by zhuovi** [comment]
Thank you for your use and feedback. I hope it will bring greater convenience to your work. There are many functions in the XiaoFeng class library. Please refer to the use methods in the wiki.
